# Generated by Django 4.2.7 on 2023-11-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='fecha_amision',
            new_name='fecha_emision',
        ),
    ]
