# Generated by Django 4.2.7 on 2023-11-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('fecha_amision', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('banco_emisor', models.CharField(max_length=70)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('tarjeta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarjetas.tarjeta')),
                ('tipo_tarjeta', models.CharField(default='CREDITO', max_length=10)),
            ],
            bases=('tarjetas.tarjeta',),
        ),
        migrations.CreateModel(
            name='TarjetaDebito',
            fields=[
                ('tarjeta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarjetas.tarjeta')),
                ('tipo_tarjeta', models.CharField(default='DEBITO', max_length=10)),
            ],
            bases=('tarjetas.tarjeta',),
        ),
    ]
