# Generated by Django 4.2.7 on 2023-11-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('tarjetas', '0002_rename_fecha_amision_tarjeta_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='banco_emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.banco'),
        ),
    ]
