# Generated by Django 4.2.7 on 2023-11-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
