# Generated by Django 4.2.7 on 2023-11-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
