# Generated by Django 4.2.7 on 2023-11-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.DecimalField(decimal_places=0, max_digits=8)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.banco')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteBlack',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('tipo_cliente', models.CharField(default='BLACK', max_length=10)),
            ],
            bases=('clientes.cliente',),
        ),
        migrations.CreateModel(
            name='ClienteClassic',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('tipo_cliente', models.CharField(default='CLASSIC', max_length=10)),
            ],
            bases=('clientes.cliente',),
        ),
        migrations.CreateModel(
            name='ClienteGold',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('tipo_cliente', models.CharField(default='GOLD', max_length=10)),
            ],
            bases=('clientes.cliente',),
        ),
    ]
