# Generated by Django 4.2.7 on 2023-11-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteclassic',
            name='cliente_ptr',
        ),
        migrations.RemoveField(
            model_name='clientegold',
            name='cliente_ptr',
        ),
        migrations.DeleteModel(
            name='ClienteBlack',
        ),
        migrations.DeleteModel(
            name='ClienteClassic',
        ),
        migrations.DeleteModel(
            name='ClienteGold',
        ),
    ]
