# Generated by Django 4.2.7 on 2023-11-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='total',
            new_name='monto_aprobado',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(default='2023-11-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prestamos.prestamo')),
            ],
        ),
    ]
