# Generated by Django 4.2.7 on 2023-11-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_cuenta_tipo_cuenta_tipo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_cliente',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('CUENTA CORRIENTE EN PESOS', 'CUENTA CORRIENTE EN PESOS'), ('CUENTA CORRIENTE EN DÓLARES', 'CUENTA CORRIENTE EN DÓLARES'), ('CAJA DE AHORRO EN PESOS', 'CAJA DE AHORRO EN PESOS'), ('CAJA DE AHORRO EN DÓLARES', 'CAJA DE AHORRO EN DÓLARES'), ('CUENTA INVERSIÓN', 'CUENTA INVERSIÓN')], default='CUENTA CORRIENTE EN PESOS', max_length=50),
        ),
    ]
