# Generated by Django 4.2.7 on 2023-11-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo_cliente',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('GOLD', 'GOLD'), ('CLASSIC', 'CLASSIC')], default='CLASSIC', max_length=10),
        ),
    ]
